Fix tautological comparison in Vec.h
../../../lib/ts/Vec.h:188:18: error: comparison of unsigned expression >= 0 is always true
[-Werror,-Wtautological-compare]
  if (i < n && i >= 0)
                 ~ ^  ~

i is of type size_t which is unsigned, so it is always >= 0.