-std=c++20: Remove TextView space before _sv/_tv literal (#12164)
Spaces before _sv literals in operator"" declarations are deprecated for
-std=c++20. This removes those spaces in the TextView.h declarations.

This addresses the following warning:

```
include/swoc/TextView.h:2088:12: error: identifier '_sv' preceded by whitespace in a literal operator declaration is deprecated [-Werror,-Wdeprecated-literal-operator]
 2088 | operator"" _sv(const char *s, size_t n) {
      | ~~~~~~~~~~~^~~
      | operator""_sv
include/swoc/TextView.h:2103:12: error: identifier '_tv' preceded by whitespace in a literal operator declaration is deprecated [-Werror,-Wdeprecated-literal-operator]
 2103 | operator"" _tv(const char *s, size_t n) {
      | ~~~~~~~~~~~^~~
      | operator""_tv
```

(cherry picked from commit eebff8b7d34b0899b02592393bc8b7827ff5597e)