Fix build on i386 caused by type mismatch
It seems lua_Integer is 32-Bit on i386 while it's 54-Bit on x86-64
causing the existing code to fail with:

metrics.cc: In function ‘bool metrics_binding_initialize(BindingInstance&)’:
metrics.cc:339:58: error: call of overloaded ‘bind_constant(const char [20], int64_t)’ is ambiguous
   binding.bind_constant("metrics.update.pass", int64_t(0));