Add CurlCommand to autests (#12122) (#12157)
* Add CurlCommand to autests (#12122)

* Add CurlCommand to autests

* MakeCurlCommand, SpawnCurlCommand, quote spaces

* separate curl and use rundir for uds path

---------

Co-authored-by: Serris Lew <lserris@apple.com>
(cherry picked from commit 35735bdee88f73ede563fc7e5bb3ad672e6f8c11)

* remove -custom from url in slice test

* autest updates for recent curl and nghttp2 versions (#12165)

* number_of_redirects.test.py: curl verbosity change

Change curl verbosity of number_of_redirects.test.py to -v from -vvv
since in later versions of curl, the output of -vvv no longer matches
the gold file.

* chunked_encoding_h2: make content-length search specific

Later versions of nghttp2 now include content-length headers in the
request generated by chunked_encoding_h2. Therefore the search strings
for the responses have to be more specific to look in server responses
only otherwise they see the content-length in the request and
incorrectly fail.

* compress.test.py: update for recent curl output

Recent versions of curl add a 'using HTTP/2' string to the output that
the compress.test.py test has to filter out.

* connect.test.py: accommodate curl output order changes

Recent versions of curl switch the order of the "Connected to" CONNECT
information with respect to the rest of the verbose output content. This
updates the test expectations to accommodate that.

* cripts autests updates

This allows the cripts.test.py file to work in generic environments
rather than just those that install into /tmp/ats.

* polite_hook_wait.test.py: update for recent curl output

Update the polite_hook_wait.test.py so that it can handle recent curl
output that adds a 'using HTTP/1.x' or similar strings to the output.

* test_TSHttpSsnInfo.test.py: accommodate nghttp

The latest version of nghttp2 has different output that the
test_TSHttpSsnInfo.test.py gold file has to be updated to accommodate.
This updates it so that it can work for newer and older versions of the
tool.

(cherry picked from commit 73670a3c6cf83c3eb01b9d62e15e37b3698075f7)

* -std=c++20: Remove TextView space before _sv/_tv literal (#12164)

Spaces before _sv literals in operator"" declarations are deprecated for
-std=c++20. This removes those spaces in the TextView.h declarations.

This addresses the following warning:

```
include/swoc/TextView.h:2088:12: error: identifier '_sv' preceded by whitespace in a literal operator declaration is deprecated [-Werror,-Wdeprecated-literal-operator]
 2088 | operator"" _sv(const char *s, size_t n) {
      | ~~~~~~~~~~~^~~
      | operator""_sv
include/swoc/TextView.h:2103:12: error: identifier '_tv' preceded by whitespace in a literal operator declaration is deprecated [-Werror,-Wdeprecated-literal-operator]
 2103 | operator"" _tv(const char *s, size_t n) {
      | ~~~~~~~~~~~^~~
      | operator""_tv
```

(cherry picked from commit eebff8b7d34b0899b02592393bc8b7827ff5597e)

* More custom

---------

Co-authored-by: Serris Lew <serrisnlew@gmail.com>
Co-authored-by: Brian Neradt <brian.neradt@gmail.com>