Fix warnings from clang 18 (#11191)
* Disable variable length array warnings

clang 18 warns about the use of dynamic variables used as the size of
arrays on the stack. We use this in a variety of places. I'm addressing
this by simply disabling the warning for now since we have used these
forever and my feel is that the community is OK with it. Some possible
alternatives would be to use alloca or to move this memory to the heap
via std::vector, but that, if desired, can be done in a separate patch.

Example warning:

src/api/InkAPI.cc:8421:16: error: variable length arrays in C++ are a Clang extension [-Werror,-Wvla-cxx-extension]
 8421 |       char buf[sid->len * 2 + 1];
      |                ^~~~~~~~~~~~~~~~
src/api/InkAPI.cc:8421:16: note: read of non-constexpr variable 'sid' is not allowed in a constant expression
src/api/InkAPI.cc:8420:27: note: declared here
 8420 |       const SSLSessionID *sid = reinterpret_cast<const SSLSessionID *>(session_id);
      |                           ^

* std::result_of -> std::invoke_result

std::result_of has been deprecated since c++17 with users encouraged to
move to std::invoke_result instead. clang 18 warns of this. This patch
transitions us to the std::invoke_result API.

Example warning:

/usr/bin/../lib/gcc/aarch64-redhat-linux/14/../../../../include/c++/14/type_traits:2708:5: error: 'result_of<(lambda at plugins/experimental/txn_box/plugin/include/txn_box/common.h:223:71) (unsigned long)>' is deprecated: u
se 'std::invoke_result' instead [-Werror,-Wdeprecated-declarations]                                                                                                                                                                                                                      2708 |     using result_of_t = typename result_of<_Tp>::type;
      |     ^
plugins/experimental/txn_box/plugin/include/txn_box/common.h:204:26: note: in instantiation of template type alias 'result_of_t' requested here
  204 |   return std::array<std::result_of_t<GENERATOR(size_t)>, sizeof...(IDX)>{g(IDX)...};
      |                          ^

* std::shared_ptr::unique -> std::shared_ptr::use_count

std::shared_ptr::unique is deprecated since c++17 since it is
approximate in multithreaded environments. The inliner plugin made use
of unique. The one place that it used unique positively to reset data
it does so under a lock, so that seems safe. The other use of unique
was to compare !unique in such a way that seems flexible with the result
being approximate anyway. So from my inspection, it seems safe to simply
transition to use_count.