doc: Fix ssl.server.{cert,private_key}.path examples
Quotes are not needed and they actually force ATS to use a wrong path:
ERROR: failed to load certificate chain from /usr/"/opt/ts/etc/ssl/certs/"/rsa.crt

(cherry picked from commit 405ce9f5791746a5b91e90db3d7649aa8ba2b2e5)