TS-3806 Resolve undefined reference to symbol MD5_Final
This is similar to TS-3632

This closes #266

(cherry picked from commit 35f11dd5aab06364547d423e26b3d5bc31c4b1e1)