header_rewrite: Improve URL Error messages (#13261)
Old log:
ERROR: [header_rewrite] Rule not supported at this hook

New log:
ERROR: [header_rewrite] Rule not supported at hook=TS_HTTP_READ_RESPONSE_HDR_HOOK: %{TO-URL:URL} in /tmp/sb/header_rewrite_unsupported_url_hook/unsupported_url_hook.conf:18

(cherry picked from commit 46413e8303cd8467c4f8267fb529e00e0472b58e)