Fix build for clang 20 (#12202)
Fix these warnings:

lib/swoc/src/swoc_ip.cc:242:10: error: first argument in call to 'memset' is a pointer to non-trivially copyable type 'swoc::IPEndpoint' [-Werror,-Wnontrivial-memaccess]
  242 |   memset(this, 0, sizeof(*this));
      |          ^

(cherry picked from commit 0da9114ff940049a57edfef55ba855d5518cd721)